
name: Run Python CI

on: [push]

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Run Python CI pipeline
        run: python ci_pipeline.py
      
      - name: Upload Build Log
        uses: actions/upload-artifact@v4
        with:
          name: ci-log
          path: build.log